/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package effyis.partners.p2s.shared.avro.meta.input;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Information about the card used in the transaction */
@org.apache.avro.specific.AvroGenerated
public class Card extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7940321648377684220L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Card\",\"namespace\":\"effyis.partners.p2s.shared.avro.meta.input\",\"doc\":\"Information about the card used in the transaction\",\"fields\":[{\"name\":\"issuerBin\",\"type\":\"string\",\"doc\":\"Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Card> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Card> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Card> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Card> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Card> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Card to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Card from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Card instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Card fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015) */
  private java.lang.CharSequence issuerBin;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Card() {}

  /**
   * All-args constructor.
   * @param issuerBin Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015)
   */
  public Card(java.lang.CharSequence issuerBin) {
    this.issuerBin = issuerBin;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return issuerBin;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: issuerBin = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'issuerBin' field.
   * @return Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015)
   */
  public java.lang.CharSequence getIssuerBin() {
    return issuerBin;
  }


  /**
   * Sets the value of the 'issuerBin' field.
   * Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015)
   * @param value the value to set.
   */
  public void setIssuerBin(java.lang.CharSequence value) {
    this.issuerBin = value;
  }

  /**
   * Creates a new Card RecordBuilder.
   * @return A new Card RecordBuilder
   */
  public static effyis.partners.p2s.shared.avro.meta.input.Card.Builder newBuilder() {
    return new effyis.partners.p2s.shared.avro.meta.input.Card.Builder();
  }

  /**
   * Creates a new Card RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Card RecordBuilder
   */
  public static effyis.partners.p2s.shared.avro.meta.input.Card.Builder newBuilder(effyis.partners.p2s.shared.avro.meta.input.Card.Builder other) {
    if (other == null) {
      return new effyis.partners.p2s.shared.avro.meta.input.Card.Builder();
    } else {
      return new effyis.partners.p2s.shared.avro.meta.input.Card.Builder(other);
    }
  }

  /**
   * Creates a new Card RecordBuilder by copying an existing Card instance.
   * @param other The existing instance to copy.
   * @return A new Card RecordBuilder
   */
  public static effyis.partners.p2s.shared.avro.meta.input.Card.Builder newBuilder(effyis.partners.p2s.shared.avro.meta.input.Card other) {
    if (other == null) {
      return new effyis.partners.p2s.shared.avro.meta.input.Card.Builder();
    } else {
      return new effyis.partners.p2s.shared.avro.meta.input.Card.Builder(other);
    }
  }

  /**
   * RecordBuilder for Card instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Card>
    implements org.apache.avro.data.RecordBuilder<Card> {

    /** Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015) */
    private java.lang.CharSequence issuerBin;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(effyis.partners.p2s.shared.avro.meta.input.Card.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.issuerBin)) {
        this.issuerBin = data().deepCopy(fields()[0].schema(), other.issuerBin);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Card instance
     * @param other The existing instance to copy.
     */
    private Builder(effyis.partners.p2s.shared.avro.meta.input.Card other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.issuerBin)) {
        this.issuerBin = data().deepCopy(fields()[0].schema(), other.issuerBin);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'issuerBin' field.
      * Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015)
      * @return The value.
      */
    public java.lang.CharSequence getIssuerBin() {
      return issuerBin;
    }


    /**
      * Sets the value of the 'issuerBin' field.
      * Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015)
      * @param value The value of 'issuerBin'.
      * @return This builder.
      */
    public effyis.partners.p2s.shared.avro.meta.input.Card.Builder setIssuerBin(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.issuerBin = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'issuerBin' field has been set.
      * Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015)
      * @return True if the 'issuerBin' field has been set, false otherwise.
      */
    public boolean hasIssuerBin() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'issuerBin' field.
      * Issuer Bank Identification Number for detecting card type, region, and rules (P2S-00015)
      * @return This builder.
      */
    public effyis.partners.p2s.shared.avro.meta.input.Card.Builder clearIssuerBin() {
      issuerBin = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Card build() {
      try {
        Card record = new Card();
        record.issuerBin = fieldSetFlags()[0] ? this.issuerBin : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Card>
    WRITER$ = (org.apache.avro.io.DatumWriter<Card>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Card>
    READER$ = (org.apache.avro.io.DatumReader<Card>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.issuerBin);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.issuerBin = in.readString(this.issuerBin instanceof Utf8 ? (Utf8)this.issuerBin : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.issuerBin = in.readString(this.issuerBin instanceof Utf8 ? (Utf8)this.issuerBin : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










